// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML.Trainers.LightGbm;
using Microsoft.ML;

namespace MapMaven_Core
{
    public partial class ScoreSaberScoreEstimateMLModel
    {
        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process. For more information on how to load data, see aka.ms/loaddata.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainPipeline(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"PP", @"PP"),new InputOutputColumnPair(@"StarDifficulty", @"StarDifficulty")})      
                                    .Append(mlContext.Transforms.Conversion.ConvertType(@"TimeSet", @"TimeSet"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"PP",@"StarDifficulty",@"TimeSet"}))      
                                    .Append(mlContext.Regression.Trainers.LightGbm(new LightGbmRegressionTrainer.Options(){NumberOfLeaves=4,NumberOfIterations=7513,MinimumExampleCountPerLeaf=38,LearningRate=0.0509562245681071,LabelColumnName=@"Accuracy",FeatureColumnName=@"Features",ExampleWeightColumnName=null,Booster=new GradientBooster.Options(){SubsampleFraction=0.166397801335603,FeatureFraction=0.855846180562251,L1Regularization=5.46085566422237E-08,L2Regularization=0.280650436522046},MaximumBinCountPerFeature=307}));

            return pipeline;
        }
    }
}
